env:
  global:
  - secure: tWyPHWMNvdCjBTdSRmaKYnendLiRd88ZIAKqQjvFXL4JHvPdBTbZgJUL5V9/e3hE+l3C2ydXWbkbdmgkuMUdBd+GFJ10KWv85TDd+JuSyODJqJPk85paqHLZKwzH2Eh4KJZQAeis69rRCvu1OwoOmZvZdiYZ/WeQBE7qWNAN3ETIler9rSWixlJMglqgFtSVxpf4W4tY2IVGt4GBtoY9ae32+CCt/8rRW4AtvI1Gix0X+JuMGeZ1tTxJh3kR3GyypWZvi2VyfocWxe8qWMMf7lp6DROFhDATCqkNgEn/EidhldILxXC9ppkF/gz1pfw8u0/VgXln9y9i/102jk+9CFedUhJWOvuOtQYmrcDFcR4vfpUW1AUZH1S1vy2ze0lwnzVveNZzwpxZa9XELnjB/FVl8AJhzISnm/6AOvy9ttrD8hzQeuxSPO8w+AwdhPp09bh+GOUGazJvieMRUv6nsrEM5RAToP0ManTUx0jBEK7A0fAlkNcrF2QjFIlSNid+XN8LWkxRF/mmq4l0wb1GEjA9eBWYaSqqHozAj9XiYPsOPA4ygIRtHNd0/g1hELKHyQUAV76xFe2LwOKse4ege6OerVrvKYRKDhfWl+mrYzhS7WVrjkerlBQXCJ+pe26d/1COAfQTBu0DHDVu0MM12rz34xHnGNnXGtb+oA43khE=
  - secure: diRKowOQi7KP1Oira5LNzGXx3x0NSLg/xLXAbqNMZokdqmE/Li4q+BUMm9yvEGJg4vAWrS1MzUaY0XsDYSE6TghDgVl8v7rRDoclpvfL4ER0s89fZysUQdXuJiaT2u22XXDY4YTpuHSnEU+PRtedY9Asa36aOqAck9AjQ5yEIeKQj/fGBv0EbdkNGA2174ZA1wb2aatlYHCGr2uHEw4w/Q8I73dHB4N59K7YcKymfWiTmmNcAY+HhEUpMBxtR+YI3XsDO8g46mtdPDSysw76Y+lQ3UEclPVZ/Q9h8LyBMfCU/w/ublHVtexgf3ROIaKsW1b4jnHxXCIUwR18M//T4yhvlFYf7uGkIyOsKmhX44HsCiOUtkWj+U/mMs3AA/9Fse8MEG8tKDLt+bATLES2NgB+cJXl1jY5i6e0vC1AYTRtN9+ilvXuQBzBm4LaPRouXess7clDUHcotMUYpgjzqPd9qfI1vTy775RkzH9CIWhF77LDcHJDoIubv7dknhX6v3lsCCVjqrzK/9SSHbIT0ehfVrr6GNbN1yvyrtBW5PYbvjQK1bX/xTz6DR/cwR0WPlSbQUEyxt71Cu1EJv1ByzZbvndoiwQ+W+JNkH3Vc7xrDjTfVUnXMZ2IVtK9J58QIizTDsk5orw1DS7bHrD+gCsyG0ezPBFv/V9N80Wse4M=
services:
- docker
script:
- docker build -t openhab-cloud .
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
    docker tag openhab-cloud $TRAVIS_REPO_SLUG:latest;
    docker push $TRAVIS_REPO_SLUG:latest;
  fi
- if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
    docker tag openhab-cloud $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
    docker push $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
  fi