# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Mehmet Arziman

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf

# Set the working directory
#WORKDIR /openhabcloud/openhab-cloud