# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Mehmet Arziman

# Copy custom configuration file from the current directory
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf