version: '3'
services:
    app-1:
        container_name: app-1
        image: docker.io/openhab/openhabcloud-app
        working_dir: /opt/openhabcloud
        networks:
        - ohcloud-network
        links:
        - mongodb
        - redis
        ports:
        - "3000"
        depends_on:
        - mongodb
        - redis  
        restart: always     
    mongodb:
        container_name: mongodb
        image: bitnami/mongodb:latest
        ports:
        - "27017:27017"
        command: mongod --smallfiles --bind_ip_all
        networks:
        - ohcloud-network
        volumes:
        - /data/db
        - /data/configdb
        restart: always
    redis:
        container_name: redis
        image: bitnami/redis:latest
        networks:
        - ohcloud-network
        ports:
        - "6379"
        environment:
        - REDIS_PASSWORD=123_openHAB
        restart: always
    nginx:
        container_name: nginx
        image: docker.io/openhab/openhabcloud-nginx
        volumes:
        - app-1:/opt/openhabcloud
        networks:
        - ohcloud-network
        ports:
        - "80:8081"
        - "443:8443"
        links:
        - app-1:app-1
volumes:
  app-1:
networks:
  ohcloud-network:
    driver: bridge